API_BASE_URL = 'https://api.example.com'
TIMEOUT = 30
RETRY_COUNT = 3
STATUS_SUCCESS = 'success'
STATUS_FAILURE = 'failure'
ERROR_INVALID_INPUT = 'Invalid input provided'
ERROR_NOT_FOUND = 'Resource not found'
ERROR_TIMEOUT = 'Operation timed out'
DEFAULT_LANGUAGE = 'en'
DEFAULT_PAGE_SIZE = 25
SUPPORTED_LANGUAGES = ['en', 'es', 'fr', 'de', 'zh']
FILE_EXTENSIONS = ['.txt', '.csv', '.json', '.xml']